version: '3'

services:
  sonarqube-custom:
    build: ./sonar
    ports:
      - "9000:9000"
    networks:
      - vpcopeninsurance
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - ./sonar/scripts/:/opt/sonarqube/scripts
    healthcheck:
      test: "curl -s -X GET localhost:9000/api/system/status"
      interval: 5s
      timeout: 3s
      retries: 30
    entrypoint: [ "bash", "./scripts/entrypoint.bash" ]

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-admin!}
      MONGO_INITDB_DATABASE: opincaptransacional
    volumes:
      - ./mongodb/init_mongo_user.sh:/docker-entrypoint-initdb.d/init_mongo_user.sh
      - ./mongodb/init_mongo_data_plans.js:/docker-entrypoint-initdb.d/init_mongo_data_plans.js:ro
      - ./mongodb/init_mongo_data_events.js:/docker-entrypoint-initdb.d/init_mongo_data_events.js:ro
      - ./mongodb/init_mongo_data_plan_info.js:/docker-entrypoint-initdb.d/init_mongo_data_plan_info.js:ro
      - ./mongodb/init_mongo_data_settlements.js:/docker-entrypoint-initdb.d/init_mongo_data_settlements.js:ro
      - mongo-volume:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - vpcopeninsurance

  mongo-express:
    image: mongo-express
    ports:
      - "8086:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USER:-dev}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASS:-dev!}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS:-admin!}
      ME_CONFIG_MONGODB_SERVER: mongo
    links:
      - mongo
    networks:
      - vpcopeninsurance
    restart: unless-stopped
    depends_on:
      - mongo

networks:
  vpcopeninsurance:
    ipam:
      config:
        - subnet: 10.8.0.0/27
volumes:
  mongo-volume:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
